CI: update make build log filter

diff --git a/.github/workflows/build-openwrt-gl-sft1200.yml b/.github/workflows/build-openwrt-gl-sft1200.yml
--- a/.github/workflows/build-openwrt-gl-sft1200.yml
+++ b/.github/workflows/build-openwrt-gl-sft1200.yml
@@ -68,6 +68,7 @@ jobs:
       run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         chmod +x $DIY_P1_SH
+        ls -lhX --time-style=long-iso . openwrt
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH "$CONFIG_FILE"
         sed 's/src-git-full/src-git/g' feeds.conf.default
@@ -84,6 +85,7 @@ jobs:
         [ -e files ] && mv files openwrt/files
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
         chmod +x $DIY_P2_SH
+        ls -lhX --time-style=long-iso . openwrt
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P2_SH "$CONFIG_FILE"
 
@@ -97,6 +99,7 @@ jobs:
     - name: Download package
       id: package
       run: |
+        ls -lhX --time-style=long-iso . openwrt
         cd openwrt
         make defconfig
         make download -j8
@@ -106,16 +109,21 @@ jobs:
     - name: Compile the firmware
       id: compile
       run: |
+        ls -lhX --time-style=long-iso . openwrt
         cd openwrt
         echo "__INFO: run 'make -j$(nproc) V=s' with '$(nproc)' thread compile"
         echo "__INFO: egrep -i 'ipv6|ipt6|ip6|6c|6t|nft|ipt4' .config"
         egrep -i 'ipv6|ipt6|ip6|6c|6t' .config
         echo "__INFO: egrep -i '[-_](ipt|nft)' .config"
         egrep -i '[-_](ipt|nft)' .config
-        # make -j$(nproc) || make -j1 V=s
-        # make -j$(nproc) V=s 2>&1 | tee build.log
-        make -j$(nproc) V=s > build.log 2>&1
+        # make -j$(nproc) || make -j1 V=sb
+        # make -j$(nproc) V=s > build.log 2>&1
+        make -j$(nproc) || { make -j1 V=s > build.log 2>&1; }
+        echo "__INFO: tail -n 5000 build.log"
+        tail -n 5000 build.log
+        echo "__INFO: tail -n 5000 build.log | egrep -C10 '(Collected errors|ERROR):'"
         tail -n 5000 build.log | egrep -C10 '(Collected errors|ERROR):'
+
         echo "::set-output name=status::success"
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
